/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.saran.luckyrun;

import java.awt.Color;
import java.awt.Font;
import java.util.Random;

/**
 *
 * @author test
 */
public class LuckyRun extends javax.swing.JFrame {

    /**
     * Creates new form LuckyRun
     */
    public LuckyRun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newDialog = new javax.swing.JDialog();
        lblResult = new javax.swing.JLabel();
        btnAgain = new javax.swing.JButton();
        panelResult = new javax.swing.JPanel();
        lblVal1 = new javax.swing.JLabel();
        lblVal2 = new javax.swing.JLabel();
        lblVal3 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnPress = new javax.swing.JButton();

        newDialog.setPreferredSize(new java.awt.Dimension(800, 400));
        newDialog.setSize(new java.awt.Dimension(800, 400));

        btnAgain.setText("Wonna Play Again?");
        btnAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgainActionPerformed(evt);
            }
        });

        lblVal1.setText("jLabel1");

        lblVal2.setText("jLabel2");

        lblVal3.setText("jLabel3");

        javax.swing.GroupLayout panelResultLayout = new javax.swing.GroupLayout(panelResult);
        panelResult.setLayout(panelResultLayout);
        panelResultLayout.setHorizontalGroup(
            panelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblVal1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblVal2)
                .addGap(18, 18, 18)
                .addComponent(lblVal3)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelResultLayout.setVerticalGroup(
            panelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVal1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lblVal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout newDialogLayout = new javax.swing.GroupLayout(newDialog.getContentPane());
        newDialog.getContentPane().setLayout(newDialogLayout);
        newDialogLayout.setHorizontalGroup(
            newDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newDialogLayout.createSequentialGroup()
                .addGap(0, 113, Short.MAX_VALUE)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(newDialogLayout.createSequentialGroup()
                .addGroup(newDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newDialogLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btnAgain))
                    .addGroup(newDialogLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(panelResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newDialogLayout.setVerticalGroup(
            newDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newDialogLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(720, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setBackground(new java.awt.Color(242, 15, 39));
        lblName.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(136, 53, 214));
        lblName.setText("Are you lucky?");
        lblName.setBorder(new javax.swing.border.MatteBorder(null));
        lblName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnPress.setBackground(new java.awt.Color(24, 24, 8));
        btnPress.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        btnPress.setForeground(new java.awt.Color(236, 20, 12));
        btnPress.setText("Try Me!");
        btnPress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnPress, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnPress)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPressActionPerformed
        newDialog.setVisible(true);
        int n1,n2,n3;
        Random rand= new Random();
        n1=rand.nextInt(3);
        n2=rand.nextInt(3);
        n3=rand.nextInt(3);
         Font font = new Font("Courier", Font.BOLD,20);
        lblVal1.setText(String.valueOf(n1));
        lblVal1.setFont(new Font("Courier",Font.BOLD,20));
        lblVal1.setForeground(Color.BLUE);
        lblVal2.setText(String.valueOf(n2));
        lblVal2.setFont(new Font("Courier",Font.BOLD,20));
        lblVal2.setForeground(Color.BLUE);
        lblVal3.setText(String.valueOf(n3));
        lblVal3.setFont(new Font("Courier",Font.BOLD,20));
        lblVal3.setForeground(Color.BLUE);

       
        if(n1==n2 && n2==n3)
        {
            lblResult.setText("Hurray!\nThe day is yours!");
            lblResult.setFont(font);
            lblResult.setForeground(Color.GREEN);
        }
        else
        {
            lblResult.setText("Sorry!\nMay be it's not your lucky day!");
            lblResult.setFont(font);
            lblResult.setForeground(Color.RED);
        }
    }//GEN-LAST:event_btnPressActionPerformed

    private void btnAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgainActionPerformed
        newDialog.setVisible(false);
        
    }//GEN-LAST:event_btnAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LuckyRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LuckyRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LuckyRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LuckyRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LuckyRun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgain;
    private javax.swing.JButton btnPress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblVal1;
    private javax.swing.JLabel lblVal2;
    private javax.swing.JLabel lblVal3;
    private javax.swing.JDialog newDialog;
    private javax.swing.JPanel panelResult;
    // End of variables declaration//GEN-END:variables
}
